# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AlertRuleKind1(Model):
    """Describes an Azure resource with kind.

    All required parameters must be populated in order to send to Azure.

    :param kind: Required. The kind of the alert rule. Possible values
     include: 'Scheduled', 'MicrosoftSecurityIncidentCreation', 'Fusion'
    :type kind: str or ~securityinsights.models.AlertRuleKind
    """

    _validation = {
        'kind': {'required': True},
    }

    _attribute_map = {
        'kind': {'key': 'kind', 'type': 'str'},
    }

    def __init__(self, *, kind, **kwargs) -> None:
        super(AlertRuleKind1, self).__init__(**kwargs)
        self.kind = kind
