# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataConnectorKind1(Model):
    """Describes an Azure resource with kind.

    All required parameters must be populated in order to send to Azure.

    :param kind: Required. The kind of the data connector. Possible values
     include: 'AzureActiveDirectory', 'AzureSecurityCenter',
     'MicrosoftCloudAppSecurity', 'ThreatIntelligence',
     'ThreatIntelligenceTaxii', 'Office365', 'AmazonWebServicesCloudTrail',
     'AzureAdvancedThreatProtection',
     'MicrosoftDefenderAdvancedThreatProtection'
    :type kind: str or ~securityinsights.models.DataConnectorKind
    """

    _validation = {
        'kind': {'required': True},
    }

    _attribute_map = {
        'kind': {'key': 'kind', 'type': 'str'},
    }

    def __init__(self, *, kind, **kwargs) -> None:
        super(DataConnectorKind1, self).__init__(**kwargs)
        self.kind = kind
