# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EntityKind1(Model):
    """Describes an entity with kind.

    All required parameters must be populated in order to send to Azure.

    :param kind: Required. The kind of the entity. Possible values include:
     'Account', 'Host', 'File', 'AzureResource', 'CloudApplication',
     'DnsResolution', 'FileHash', 'Ip', 'Malware', 'Process', 'RegistryKey',
     'RegistryValue', 'SecurityGroup', 'Url', 'IoTDevice', 'SecurityAlert',
     'Bookmark'
    :type kind: str or ~securityinsights.models.EntityKind
    """

    _validation = {
        'kind': {'required': True},
    }

    _attribute_map = {
        'kind': {'key': 'kind', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(EntityKind1, self).__init__(**kwargs)
        self.kind = kwargs.get('kind', None)
