# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GroupingConfiguration(Model):
    """Grouping configuration property bag.

    All required parameters must be populated in order to send to Azure.

    :param enabled: Required. Grouping enabled
    :type enabled: bool
    :param reopen_closed_incident: Required. Re-open closed matching incidents
    :type reopen_closed_incident: bool
    :param lookback_duration: Required. Limit the group to alerts created
     within the lookback duration (in ISO 8601 duration format)
    :type lookback_duration: timedelta
    :param entities_matching_method: Required. Grouping matching method.
     Possible values include: 'All', 'None', 'Custom'
    :type entities_matching_method: str or
     ~securityinsights.models.EntitiesMatchingMethod
    :param group_by_entities: A list of entity types to group by (when
     entitiesMatchingMethod is Custom)
    :type group_by_entities: list[str or
     ~securityinsights.models.GroupingEntityType]
    """

    _validation = {
        'enabled': {'required': True},
        'reopen_closed_incident': {'required': True},
        'lookback_duration': {'required': True},
        'entities_matching_method': {'required': True},
    }

    _attribute_map = {
        'enabled': {'key': 'enabled', 'type': 'bool'},
        'reopen_closed_incident': {'key': 'reopenClosedIncident', 'type': 'bool'},
        'lookback_duration': {'key': 'lookbackDuration', 'type': 'duration'},
        'entities_matching_method': {'key': 'entitiesMatchingMethod', 'type': 'str'},
        'group_by_entities': {'key': 'groupByEntities', 'type': '[str]'},
    }

    def __init__(self, *, enabled: bool, reopen_closed_incident: bool, lookback_duration, entities_matching_method, group_by_entities=None, **kwargs) -> None:
        super(GroupingConfiguration, self).__init__(**kwargs)
        self.enabled = enabled
        self.reopen_closed_incident = reopen_closed_incident
        self.lookback_duration = lookback_duration
        self.entities_matching_method = entities_matching_method
        self.group_by_entities = group_by_entities
