# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IncidentAdditionalData(Model):
    """Incident additional data property bag.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar alerts_count: The number of alerts in the incident
    :vartype alerts_count: int
    :ivar bookmarks_count: The number of bookmarks in the incident
    :vartype bookmarks_count: int
    :ivar comments_count: The number of comments in the incident
    :vartype comments_count: int
    :ivar alert_product_names: List of product names of alerts in the incident
    :vartype alert_product_names: list[str]
    :ivar tactics: The tactics associated with incident
    :vartype tactics: list[str or ~securityinsights.models.AttackTactic]
    """

    _validation = {
        'alerts_count': {'readonly': True},
        'bookmarks_count': {'readonly': True},
        'comments_count': {'readonly': True},
        'alert_product_names': {'readonly': True},
        'tactics': {'readonly': True},
    }

    _attribute_map = {
        'alerts_count': {'key': 'alertsCount', 'type': 'int'},
        'bookmarks_count': {'key': 'bookmarksCount', 'type': 'int'},
        'comments_count': {'key': 'commentsCount', 'type': 'int'},
        'alert_product_names': {'key': 'alertProductNames', 'type': '[str]'},
        'tactics': {'key': 'tactics', 'type': '[str]'},
    }

    def __init__(self, **kwargs) -> None:
        super(IncidentAdditionalData, self).__init__(**kwargs)
        self.alerts_count = None
        self.bookmarks_count = None
        self.comments_count = None
        self.alert_product_names = None
        self.tactics = None
