# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IncidentEntitiesResponse(Model):
    """The incident related entities response.

    :param entities: Array of the incident related entities.
    :type entities: list[~securityinsights.models.Entity]
    :param meta_data: The metadata from the incident related entities results.
    :type meta_data:
     list[~securityinsights.models.IncidentEntitiesResultsMetadata]
    """

    _attribute_map = {
        'entities': {'key': 'entities', 'type': '[Entity]'},
        'meta_data': {'key': 'metaData', 'type': '[IncidentEntitiesResultsMetadata]'},
    }

    def __init__(self, **kwargs):
        super(IncidentEntitiesResponse, self).__init__(**kwargs)
        self.entities = kwargs.get('entities', None)
        self.meta_data = kwargs.get('meta_data', None)
