# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .entity_py3 import Entity


class IoTDeviceEntity(Entity):
    """Represents an IoT device entity.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar id: Azure resource Id
    :vartype id: str
    :ivar name: Azure resource name
    :vartype name: str
    :ivar type: Azure resource type
    :vartype type: str
    :param kind: Required. Constant filled by server.
    :type kind: str
    :ivar additional_data: A bag of custom fields that should be part of the
     entity and will be presented to the user.
    :vartype additional_data: dict[str, object]
    :ivar friendly_name: The graph item display name which is a short humanly
     readable description of the graph item instance. This property is optional
     and might be system generated.
    :vartype friendly_name: str
    :ivar device_id: The ID of the IoT Device in the IoT Hub
    :vartype device_id: str
    :ivar iot_security_agent_id: The ID of the security agent running on the
     device
    :vartype iot_security_agent_id: str
    :ivar device_type: The type of the device
    :vartype device_type: str
    :ivar vendor: The vendor of the device
    :vartype vendor: str
    :ivar edge_id: The ID of the edge device
    :vartype edge_id: str
    :ivar iot_hub_entity_id: The AzureResource entity id of the IoT Hub
    :vartype iot_hub_entity_id: str
    :ivar host_entity_id: The Host entity id of this device
    :vartype host_entity_id: str
    :ivar threat_intelligence: A list of TI contexts attached to the IoTDevice
     entity.
    :vartype threat_intelligence:
     list[~securityinsights.models.ThreatIntelligence]
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'kind': {'required': True},
        'additional_data': {'readonly': True},
        'friendly_name': {'readonly': True},
        'device_id': {'readonly': True},
        'iot_security_agent_id': {'readonly': True},
        'device_type': {'readonly': True},
        'vendor': {'readonly': True},
        'edge_id': {'readonly': True},
        'iot_hub_entity_id': {'readonly': True},
        'host_entity_id': {'readonly': True},
        'threat_intelligence': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'kind': {'key': 'kind', 'type': 'str'},
        'additional_data': {'key': 'properties.additionalData', 'type': '{object}'},
        'friendly_name': {'key': 'properties.friendlyName', 'type': 'str'},
        'device_id': {'key': 'properties.deviceId', 'type': 'str'},
        'iot_security_agent_id': {'key': 'properties.iotSecurityAgentId', 'type': 'str'},
        'device_type': {'key': 'properties.deviceType', 'type': 'str'},
        'vendor': {'key': 'properties.vendor', 'type': 'str'},
        'edge_id': {'key': 'properties.edgeId', 'type': 'str'},
        'iot_hub_entity_id': {'key': 'properties.iotHubEntityId', 'type': 'str'},
        'host_entity_id': {'key': 'properties.hostEntityId', 'type': 'str'},
        'threat_intelligence': {'key': 'properties.threatIntelligence', 'type': '[ThreatIntelligence]'},
    }

    def __init__(self, **kwargs) -> None:
        super(IoTDeviceEntity, self).__init__(**kwargs)
        self.additional_data = None
        self.friendly_name = None
        self.device_id = None
        self.iot_security_agent_id = None
        self.device_type = None
        self.vendor = None
        self.edge_id = None
        self.iot_hub_entity_id = None
        self.host_entity_id = None
        self.threat_intelligence = None
        self.kind = 'IoTDevice'
