# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Operation(Model):
    """Operation provided by provider.

    :param display: Properties of the operation
    :type display: ~securityinsights.models.OperationDisplay
    :param name: Name of the operation
    :type name: str
    """

    _attribute_map = {
        'display': {'key': 'display', 'type': 'OperationDisplay'},
        'name': {'key': 'name', 'type': 'str'},
    }

    def __init__(self, *, display=None, name: str=None, **kwargs) -> None:
        super(Operation, self).__init__(**kwargs)
        self.display = display
        self.name = name
