# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .entity_py3 import Entity


class SecurityAlert(Entity):
    """Represents a security alert entity.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar id: Azure resource Id
    :vartype id: str
    :ivar name: Azure resource name
    :vartype name: str
    :ivar type: Azure resource type
    :vartype type: str
    :param kind: Required. Constant filled by server.
    :type kind: str
    :ivar additional_data: A bag of custom fields that should be part of the
     entity and will be presented to the user.
    :vartype additional_data: dict[str, object]
    :ivar friendly_name: The graph item display name which is a short humanly
     readable description of the graph item instance. This property is optional
     and might be system generated.
    :vartype friendly_name: str
    :ivar alert_display_name: The display name of the alert.
    :vartype alert_display_name: str
    :ivar alert_type: The type name of the alert.
    :vartype alert_type: str
    :ivar compromised_entity: Display name of the main entity being reported
     on.
    :vartype compromised_entity: str
    :ivar confidence_level: The confidence level of this alert. Possible
     values include: 'Unknown', 'Low', 'High'
    :vartype confidence_level: str or ~securityinsights.models.ConfidenceLevel
    :ivar confidence_reasons: The confidence reasons
    :vartype confidence_reasons:
     list[~securityinsights.models.SecurityAlertPropertiesConfidenceReasonsItem]
    :ivar confidence_score: The confidence score of the alert.
    :vartype confidence_score: float
    :ivar confidence_score_status: The confidence score calculation status,
     i.e. indicating if score calculation is pending for this alert, not
     applicable or final. Possible values include: 'NotApplicable',
     'InProcess', 'NotFinal', 'Final'
    :vartype confidence_score_status: str or
     ~securityinsights.models.ConfidenceScoreStatus
    :ivar description: Alert description.
    :vartype description: str
    :ivar end_time_utc: The impact end time of the alert (the time of the last
     event contributing to the alert).
    :vartype end_time_utc: datetime
    :ivar intent: Holds the alert intent stage(s) mapping for this alert.
     Possible values include: 'Unknown', 'Probing', 'Exploitation',
     'Persistence', 'PrivilegeEscalation', 'DefenseEvasion',
     'CredentialAccess', 'Discovery', 'LateralMovement', 'Execution',
     'Collection', 'Exfiltration', 'CommandAndControl', 'Impact'
    :vartype intent: str or ~securityinsights.models.KillChainIntent
    :ivar provider_alert_id: The identifier of the alert inside the product
     which generated the alert.
    :vartype provider_alert_id: str
    :ivar processing_end_time: The time the alert was made available for
     consumption.
    :vartype processing_end_time: datetime
    :ivar product_component_name: The name of a component inside the product
     which generated the alert.
    :vartype product_component_name: str
    :ivar product_name: The name of the product which published this alert.
    :vartype product_name: str
    :ivar product_version: The version of the product generating the alert.
    :vartype product_version: str
    :ivar remediation_steps: Manual action items to take to remediate the
     alert.
    :vartype remediation_steps: list[str]
    :param severity: The severity of the alert. Possible values include:
     'High', 'Medium', 'Low', 'Informational'
    :type severity: str or ~securityinsights.models.AlertSeverity
    :ivar start_time_utc: The impact start time of the alert (the time of the
     first event contributing to the alert).
    :vartype start_time_utc: datetime
    :ivar status: The lifecycle status of the alert. Possible values include:
     'Unknown', 'New', 'Resolved', 'Dismissed', 'InProgress'
    :vartype status: str or ~securityinsights.models.AlertStatus
    :ivar system_alert_id: Holds the product identifier of the alert for the
     product.
    :vartype system_alert_id: str
    :ivar tactics: The tactics of the alert
    :vartype tactics: list[str or ~securityinsights.models.AttackTactic]
    :ivar time_generated: The time the alert was generated.
    :vartype time_generated: datetime
    :ivar vendor_name: The name of the vendor that raise the alert.
    :vartype vendor_name: str
    :ivar alert_link: The uri link of the alert.
    :vartype alert_link: str
    :ivar resource_identifiers: The list of resource identifiers of the alert.
    :vartype resource_identifiers: list[object]
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'kind': {'required': True},
        'additional_data': {'readonly': True},
        'friendly_name': {'readonly': True},
        'alert_display_name': {'readonly': True},
        'alert_type': {'readonly': True},
        'compromised_entity': {'readonly': True},
        'confidence_level': {'readonly': True},
        'confidence_reasons': {'readonly': True},
        'confidence_score': {'readonly': True},
        'confidence_score_status': {'readonly': True},
        'description': {'readonly': True},
        'end_time_utc': {'readonly': True},
        'intent': {'readonly': True},
        'provider_alert_id': {'readonly': True},
        'processing_end_time': {'readonly': True},
        'product_component_name': {'readonly': True},
        'product_name': {'readonly': True},
        'product_version': {'readonly': True},
        'remediation_steps': {'readonly': True},
        'start_time_utc': {'readonly': True},
        'status': {'readonly': True},
        'system_alert_id': {'readonly': True},
        'tactics': {'readonly': True},
        'time_generated': {'readonly': True},
        'vendor_name': {'readonly': True},
        'alert_link': {'readonly': True},
        'resource_identifiers': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'kind': {'key': 'kind', 'type': 'str'},
        'additional_data': {'key': 'properties.additionalData', 'type': '{object}'},
        'friendly_name': {'key': 'properties.friendlyName', 'type': 'str'},
        'alert_display_name': {'key': 'properties.alertDisplayName', 'type': 'str'},
        'alert_type': {'key': 'properties.alertType', 'type': 'str'},
        'compromised_entity': {'key': 'properties.compromisedEntity', 'type': 'str'},
        'confidence_level': {'key': 'properties.confidenceLevel', 'type': 'str'},
        'confidence_reasons': {'key': 'properties.confidenceReasons', 'type': '[SecurityAlertPropertiesConfidenceReasonsItem]'},
        'confidence_score': {'key': 'properties.confidenceScore', 'type': 'float'},
        'confidence_score_status': {'key': 'properties.confidenceScoreStatus', 'type': 'str'},
        'description': {'key': 'properties.description', 'type': 'str'},
        'end_time_utc': {'key': 'properties.endTimeUtc', 'type': 'iso-8601'},
        'intent': {'key': 'properties.intent', 'type': 'str'},
        'provider_alert_id': {'key': 'properties.providerAlertId', 'type': 'str'},
        'processing_end_time': {'key': 'properties.processingEndTime', 'type': 'iso-8601'},
        'product_component_name': {'key': 'properties.productComponentName', 'type': 'str'},
        'product_name': {'key': 'properties.productName', 'type': 'str'},
        'product_version': {'key': 'properties.productVersion', 'type': 'str'},
        'remediation_steps': {'key': 'properties.remediationSteps', 'type': '[str]'},
        'severity': {'key': 'properties.severity', 'type': 'str'},
        'start_time_utc': {'key': 'properties.startTimeUtc', 'type': 'iso-8601'},
        'status': {'key': 'properties.status', 'type': 'str'},
        'system_alert_id': {'key': 'properties.systemAlertId', 'type': 'str'},
        'tactics': {'key': 'properties.tactics', 'type': '[str]'},
        'time_generated': {'key': 'properties.timeGenerated', 'type': 'iso-8601'},
        'vendor_name': {'key': 'properties.vendorName', 'type': 'str'},
        'alert_link': {'key': 'properties.alertLink', 'type': 'str'},
        'resource_identifiers': {'key': 'properties.resourceIdentifiers', 'type': '[object]'},
    }

    def __init__(self, *, severity=None, **kwargs) -> None:
        super(SecurityAlert, self).__init__(**kwargs)
        self.additional_data = None
        self.friendly_name = None
        self.alert_display_name = None
        self.alert_type = None
        self.compromised_entity = None
        self.confidence_level = None
        self.confidence_reasons = None
        self.confidence_score = None
        self.confidence_score_status = None
        self.description = None
        self.end_time_utc = None
        self.intent = None
        self.provider_alert_id = None
        self.processing_end_time = None
        self.product_component_name = None
        self.product_name = None
        self.product_version = None
        self.remediation_steps = None
        self.severity = severity
        self.start_time_utc = None
        self.status = None
        self.system_alert_id = None
        self.tactics = None
        self.time_generated = None
        self.vendor_name = None
        self.alert_link = None
        self.resource_identifiers = None
        self.kind = 'SecurityAlert'
