# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SettingsKind(Model):
    """Describes an Azure resource with kind.

    All required parameters must be populated in order to send to Azure.

    :param kind: Required. The kind of the setting. Possible values include:
     'EyesOn', 'EntityAnalytics', 'Ueba'
    :type kind: str or ~securityinsights.models.SettingKind
    """

    _validation = {
        'kind': {'required': True},
    }

    _attribute_map = {
        'kind': {'key': 'kind', 'type': 'str'},
    }

    def __init__(self, *, kind, **kwargs) -> None:
        super(SettingsKind, self).__init__(**kwargs)
        self.kind = kind
