# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ThreatIntelligenceKillChainPhase(Model):
    """Describes threat kill chain phase entity.

    :param kill_chain_name: Kill chainName name
    :type kill_chain_name: str
    :param phase_name: Phase name
    :type phase_name: int
    """

    _attribute_map = {
        'kill_chain_name': {'key': 'killChainName', 'type': 'str'},
        'phase_name': {'key': 'phaseName', 'type': 'int'},
    }

    def __init__(self, *, kill_chain_name: str=None, phase_name: int=None, **kwargs) -> None:
        super(ThreatIntelligenceKillChainPhase, self).__init__(**kwargs)
        self.kill_chain_name = kill_chain_name
        self.phase_name = phase_name
