# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .threat_intelligence_resource import ThreatIntelligenceResource


class ThreatIntelligenceIndicatorModel(ThreatIntelligenceResource):
    """Threat intelligence indicator entity.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar id: Azure resource Id
    :vartype id: str
    :ivar name: Azure resource name
    :vartype name: str
    :ivar type: Azure resource type
    :vartype type: str
    :param etag: Etag of the azure resource
    :type etag: str
    :param kind: Required. Constant filled by server.
    :type kind: str
    :ivar additional_data: A bag of custom fields that should be part of the
     entity and will be presented to the user.
    :vartype additional_data: dict[str, object]
    :ivar friendly_name: The graph item display name which is a short humanly
     readable description of the graph item instance. This property is optional
     and might be system generated.
    :vartype friendly_name: str
    :param threat_intelligence_tags: List of tags
    :type threat_intelligence_tags: list[str]
    :param last_updated_time_utc: Last updated time in UTC
    :type last_updated_time_utc: str
    :param source: Source of a threat intelligence entity
    :type source: str
    :param display_name: Display name of a threat intelligence entity
    :type display_name: str
    :param description: Description of a threat intelligence entity
    :type description: str
    :param indicator_types: Indicator types of threat intelligence entities
    :type indicator_types: list[str]
    :param pattern: Pattern of a threat intelligence entity
    :type pattern: str
    :param pattern_type: Pattern type of a threat intelligence entity
    :type pattern_type: str
    :param kill_chain_phases: Kill chain phases
    :type kill_chain_phases:
     list[~securityinsights.models.ThreatIntelligenceKillChainPhase]
    :param external_id: External ID of threat intelligence entity
    :type external_id: str
    :param created_by_ref: Created by reference of threat intelligence entity
    :type created_by_ref: str
    :param external_references: External References
    :type external_references: list[str]
    :param granular_markings: Granular Markings
    :type granular_markings:
     list[~securityinsights.models.ThreatIntelligenceGranularMarkingModel]
    :param revoked: Is threat intelligence entity revoked
    :type revoked: bool
    :param confidence: Confidence of threat intelligence entity
    :type confidence: int
    :param labels: Labels  of threat intelligence entity
    :type labels: list[str]
    :param threat_types: Threat types
    :type threat_types: list[str]
    :param valid_from: Valid from
    :type valid_from: str
    :param valid_until: Valid until
    :type valid_until: str
    :param created: Created by
    :type created: str
    :param modified: Modified by
    :type modified: str
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'kind': {'required': True},
        'additional_data': {'readonly': True},
        'friendly_name': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'etag': {'key': 'etag', 'type': 'str'},
        'kind': {'key': 'kind', 'type': 'str'},
        'additional_data': {'key': 'properties.additionalData', 'type': '{object}'},
        'friendly_name': {'key': 'properties.friendlyName', 'type': 'str'},
        'threat_intelligence_tags': {'key': 'properties.threatIntelligenceTags', 'type': '[str]'},
        'last_updated_time_utc': {'key': 'properties.lastUpdatedTimeUtc', 'type': 'str'},
        'source': {'key': 'properties.source', 'type': 'str'},
        'display_name': {'key': 'properties.displayName', 'type': 'str'},
        'description': {'key': 'properties.description', 'type': 'str'},
        'indicator_types': {'key': 'properties.indicatorTypes', 'type': '[str]'},
        'pattern': {'key': 'properties.pattern', 'type': 'str'},
        'pattern_type': {'key': 'properties.patternType', 'type': 'str'},
        'kill_chain_phases': {'key': 'properties.killChainPhases', 'type': '[ThreatIntelligenceKillChainPhase]'},
        'external_id': {'key': 'properties.externalId', 'type': 'str'},
        'created_by_ref': {'key': 'properties.createdByRef', 'type': 'str'},
        'external_references': {'key': 'properties.externalReferences', 'type': '[str]'},
        'granular_markings': {'key': 'properties.granularMarkings', 'type': '[ThreatIntelligenceGranularMarkingModel]'},
        'revoked': {'key': 'properties.revoked', 'type': 'bool'},
        'confidence': {'key': 'properties.confidence', 'type': 'int'},
        'labels': {'key': 'properties.labels', 'type': '[str]'},
        'threat_types': {'key': 'properties.threatTypes', 'type': '[str]'},
        'valid_from': {'key': 'properties.validFrom', 'type': 'str'},
        'valid_until': {'key': 'properties.validUntil', 'type': 'str'},
        'created': {'key': 'properties.created', 'type': 'str'},
        'modified': {'key': 'properties.modified', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ThreatIntelligenceIndicatorModel, self).__init__(**kwargs)
        self.additional_data = None
        self.friendly_name = None
        self.threat_intelligence_tags = kwargs.get('threat_intelligence_tags', None)
        self.last_updated_time_utc = kwargs.get('last_updated_time_utc', None)
        self.source = kwargs.get('source', None)
        self.display_name = kwargs.get('display_name', None)
        self.description = kwargs.get('description', None)
        self.indicator_types = kwargs.get('indicator_types', None)
        self.pattern = kwargs.get('pattern', None)
        self.pattern_type = kwargs.get('pattern_type', None)
        self.kill_chain_phases = kwargs.get('kill_chain_phases', None)
        self.external_id = kwargs.get('external_id', None)
        self.created_by_ref = kwargs.get('created_by_ref', None)
        self.external_references = kwargs.get('external_references', None)
        self.granular_markings = kwargs.get('granular_markings', None)
        self.revoked = kwargs.get('revoked', None)
        self.confidence = kwargs.get('confidence', None)
        self.labels = kwargs.get('labels', None)
        self.threat_types = kwargs.get('threat_types', None)
        self.valid_from = kwargs.get('valid_from', None)
        self.valid_until = kwargs.get('valid_until', None)
        self.created = kwargs.get('created', None)
        self.modified = kwargs.get('modified', None)
        self.kind = 'indicator'
