# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ThreatIntelligenceMetricResource(Model):
    """Threat intelligence metric resource.

    :param properties: Threat intelligence metric.
    :type properties: ~securityinsights.models.ThreatIntelligenceMetric
    """

    _attribute_map = {
        'properties': {'key': 'properties', 'type': 'ThreatIntelligenceMetric'},
    }

    def __init__(self, *, properties=None, **kwargs) -> None:
        super(ThreatIntelligenceMetricResource, self).__init__(**kwargs)
        self.properties = properties
