# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ThreatIntelligenceArmStixQuery(Model):
    """Describes threat intelligence ARM STIX query.

    :param page_size: Page size
    :type page_size: int
    :param min_confidence: Minimum confidence
    :type min_confidence: int
    :param max_confidence: Maximum confidence
    :type max_confidence: int
    :param min_valid_until: Minimum Valid until
    :type min_valid_until: str
    :param max_valid_until: Maximum Valid until
    :type max_valid_until: str
    :param include_disabled: To include disabled indicators
    :type include_disabled: bool
    :param sort_by: List of Sort rules
    :type sort_by:
     list[~securityinsights.models.ThreatIntelligenceArmStixSortBy1]
    :param sources: Sources of a threat intelligence entity
    :type sources: list[str]
    :param pattern_types: Pattern types
    :type pattern_types: list[str]
    :param threat_types: Threat types
    :type threat_types: list[str]
    :param ids: Ids of threat intelligence entities
    :type ids: list[str]
    :param keywords: Keywords of threat intelligence entities
    :type keywords: list[str]
    :param skip_token: Skip Token
    :type skip_token: str
    """

    _attribute_map = {
        'page_size': {'key': 'pageSize', 'type': 'int'},
        'min_confidence': {'key': 'minConfidence', 'type': 'int'},
        'max_confidence': {'key': 'maxConfidence', 'type': 'int'},
        'min_valid_until': {'key': 'minValidUntil', 'type': 'str'},
        'max_valid_until': {'key': 'maxValidUntil', 'type': 'str'},
        'include_disabled': {'key': 'includeDisabled', 'type': 'bool'},
        'sort_by': {'key': 'sortBy', 'type': '[ThreatIntelligenceArmStixSortBy1]'},
        'sources': {'key': 'sources', 'type': '[str]'},
        'pattern_types': {'key': 'patternTypes', 'type': '[str]'},
        'threat_types': {'key': 'threatTypes', 'type': '[str]'},
        'ids': {'key': 'ids', 'type': '[str]'},
        'keywords': {'key': 'keywords', 'type': '[str]'},
        'skip_token': {'key': 'skipToken', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ThreatIntelligenceArmStixQuery, self).__init__(**kwargs)
        self.page_size = kwargs.get('page_size', None)
        self.min_confidence = kwargs.get('min_confidence', None)
        self.max_confidence = kwargs.get('max_confidence', None)
        self.min_valid_until = kwargs.get('min_valid_until', None)
        self.max_valid_until = kwargs.get('max_valid_until', None)
        self.include_disabled = kwargs.get('include_disabled', None)
        self.sort_by = kwargs.get('sort_by', None)
        self.sources = kwargs.get('sources', None)
        self.pattern_types = kwargs.get('pattern_types', None)
        self.threat_types = kwargs.get('threat_types', None)
        self.ids = kwargs.get('ids', None)
        self.keywords = kwargs.get('keywords', None)
        self.skip_token = kwargs.get('skip_token', None)
