# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ThreatIntelligenceAppendTagsRequestBody(Model):
    """Describes threat intelligence indicator append tags request body.

    :param threat_intelligence_tags: List of threat intelligence tags
    :type threat_intelligence_tags: list[str]
    """

    _attribute_map = {
        'threat_intelligence_tags': {'key': 'threatIntelligenceTags', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(ThreatIntelligenceAppendTagsRequestBody, self).__init__(**kwargs)
        self.threat_intelligence_tags = kwargs.get('threat_intelligence_tags', None)
