# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .threat_intelligence_resource_kind1_py3 import ThreatIntelligenceResourceKind1


class ThreatIntelligenceIndicatorWithoutReadOnlyFields(ThreatIntelligenceResourceKind1):
    """Threat intelligence indicator entity.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar kind: Required. The kind of the entity. Default value: "indicator" .
    :vartype kind: str
    :param etag: Etag of the azure resource
    :type etag: str
    :ivar additional_data: A bag of custom fields that should be part of the
     entity and will be presented to the user.
    :vartype additional_data: dict[str, object]
    :ivar friendly_name: The graph item display name which is a short humanly
     readable description of the graph item instance. This property is optional
     and might be system generated.
    :vartype friendly_name: str
    :param threat_intelligence_tags: List of tags
    :type threat_intelligence_tags: list[str]
    :param last_updated_time_utc: Last updated time in UTC
    :type last_updated_time_utc: str
    :param source: Source of a threat intelligence entity
    :type source: str
    :param display_name: Display name of a threat intelligence entity
    :type display_name: str
    :param description: Description of a threat intelligence entity
    :type description: str
    :param indicator_types: Indicator types of threat intelligence entities
    :type indicator_types: list[str]
    :param pattern: Pattern of a threat intelligence entity
    :type pattern: str
    :param pattern_type: Pattern type of a threat intelligence entity
    :type pattern_type: str
    :param kill_chain_phases: Kill chain phases
    :type kill_chain_phases:
     list[~securityinsights.models.ThreatIntelligenceKillChainPhase]
    :param external_id: External ID of threat intelligence entity
    :type external_id: str
    :param created_by_ref: Created by reference of threat intelligence entity
    :type created_by_ref: str
    :param external_references: External References
    :type external_references: list[str]
    :param granular_markings: Granular Markings
    :type granular_markings:
     list[~securityinsights.models.ThreatIntelligenceGranularMarkingModel]
    :param revoked: Is threat intelligence entity revoked
    :type revoked: bool
    :param confidence: Confidence of threat intelligence entity
    :type confidence: int
    :param labels: Labels  of threat intelligence entity
    :type labels: list[str]
    :param threat_types: Threat types
    :type threat_types: list[str]
    :param valid_from: Valid from
    :type valid_from: str
    :param valid_until: Valid until
    :type valid_until: str
    :param created: Created by
    :type created: str
    :param modified: Modified by
    :type modified: str
    """

    _validation = {
        'kind': {'required': True, 'constant': True},
        'additional_data': {'readonly': True},
        'friendly_name': {'readonly': True},
    }

    _attribute_map = {
        'kind': {'key': 'kind', 'type': 'str'},
        'etag': {'key': 'etag', 'type': 'str'},
        'additional_data': {'key': 'properties.additionalData', 'type': '{object}'},
        'friendly_name': {'key': 'properties.friendlyName', 'type': 'str'},
        'threat_intelligence_tags': {'key': 'properties.threatIntelligenceTags', 'type': '[str]'},
        'last_updated_time_utc': {'key': 'properties.lastUpdatedTimeUtc', 'type': 'str'},
        'source': {'key': 'properties.source', 'type': 'str'},
        'display_name': {'key': 'properties.displayName', 'type': 'str'},
        'description': {'key': 'properties.description', 'type': 'str'},
        'indicator_types': {'key': 'properties.indicatorTypes', 'type': '[str]'},
        'pattern': {'key': 'properties.pattern', 'type': 'str'},
        'pattern_type': {'key': 'properties.patternType', 'type': 'str'},
        'kill_chain_phases': {'key': 'properties.killChainPhases', 'type': '[ThreatIntelligenceKillChainPhase]'},
        'external_id': {'key': 'properties.externalId', 'type': 'str'},
        'created_by_ref': {'key': 'properties.createdByRef', 'type': 'str'},
        'external_references': {'key': 'properties.externalReferences', 'type': '[str]'},
        'granular_markings': {'key': 'properties.granularMarkings', 'type': '[ThreatIntelligenceGranularMarkingModel]'},
        'revoked': {'key': 'properties.revoked', 'type': 'bool'},
        'confidence': {'key': 'properties.confidence', 'type': 'int'},
        'labels': {'key': 'properties.labels', 'type': '[str]'},
        'threat_types': {'key': 'properties.threatTypes', 'type': '[str]'},
        'valid_from': {'key': 'properties.validFrom', 'type': 'str'},
        'valid_until': {'key': 'properties.validUntil', 'type': 'str'},
        'created': {'key': 'properties.created', 'type': 'str'},
        'modified': {'key': 'properties.modified', 'type': 'str'},
    }

    def __init__(self, *, etag: str=None, threat_intelligence_tags=None, last_updated_time_utc: str=None, source: str=None, display_name: str=None, description: str=None, indicator_types=None, pattern: str=None, pattern_type: str=None, kill_chain_phases=None, external_id: str=None, created_by_ref: str=None, external_references=None, granular_markings=None, revoked: bool=None, confidence: int=None, labels=None, threat_types=None, valid_from: str=None, valid_until: str=None, created: str=None, modified: str=None, **kwargs) -> None:
        super(ThreatIntelligenceIndicatorWithoutReadOnlyFields, self).__init__(**kwargs)
        self.etag = etag
        self.additional_data = None
        self.friendly_name = None
        self.threat_intelligence_tags = threat_intelligence_tags
        self.last_updated_time_utc = last_updated_time_utc
        self.source = source
        self.display_name = display_name
        self.description = description
        self.indicator_types = indicator_types
        self.pattern = pattern
        self.pattern_type = pattern_type
        self.kill_chain_phases = kill_chain_phases
        self.external_id = external_id
        self.created_by_ref = created_by_ref
        self.external_references = external_references
        self.granular_markings = granular_markings
        self.revoked = revoked
        self.confidence = confidence
        self.labels = labels
        self.threat_types = threat_types
        self.valid_from = valid_from
        self.valid_until = valid_until
        self.created = created
        self.modified = modified
