# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .data_connector import DataConnector


class TiTaxiiDataConnector(DataConnector):
    """Represents threat intelligence taxii data connector.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar id: Azure resource Id
    :vartype id: str
    :ivar name: Azure resource name
    :vartype name: str
    :ivar type: Azure resource type
    :vartype type: str
    :param etag: Etag of the azure resource
    :type etag: str
    :param kind: Required. Constant filled by server.
    :type kind: str
    :param tenant_id: The tenant id to connect to, and get the data from.
    :type tenant_id: str
    :param workspace_id: The workspace id.
    :type workspace_id: str
    :param friendly_name: The friendly name for taxii client connector.
    :type friendly_name: str
    :param taxii_server: The API root server for taxii client.
    :type taxii_server: str
    :param collection_id: The taxii collection id.
    :type collection_id: str
    :param user_name: The taxii server user name.
    :type user_name: str
    :param password: The taxii server password.
    :type password: str
    :param data_types: The available data types for the connector.
    :type data_types: ~securityinsights.models.TiTaxiiDataConnectorDataTypes
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'kind': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'etag': {'key': 'etag', 'type': 'str'},
        'kind': {'key': 'kind', 'type': 'str'},
        'tenant_id': {'key': 'properties.tenantId', 'type': 'str'},
        'workspace_id': {'key': 'properties.workspaceId', 'type': 'str'},
        'friendly_name': {'key': 'properties.friendlyName', 'type': 'str'},
        'taxii_server': {'key': 'properties.taxiiServer', 'type': 'str'},
        'collection_id': {'key': 'properties.collectionId', 'type': 'str'},
        'user_name': {'key': 'properties.userName', 'type': 'str'},
        'password': {'key': 'properties.password', 'type': 'str'},
        'data_types': {'key': 'properties.dataTypes', 'type': 'TiTaxiiDataConnectorDataTypes'},
    }

    def __init__(self, **kwargs):
        super(TiTaxiiDataConnector, self).__init__(**kwargs)
        self.tenant_id = kwargs.get('tenant_id', None)
        self.workspace_id = kwargs.get('workspace_id', None)
        self.friendly_name = kwargs.get('friendly_name', None)
        self.taxii_server = kwargs.get('taxii_server', None)
        self.collection_id = kwargs.get('collection_id', None)
        self.user_name = kwargs.get('user_name', None)
        self.password = kwargs.get('password', None)
        self.data_types = kwargs.get('data_types', None)
        self.kind = 'ThreatIntelligenceTaxii'
