# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TiTaxiiDataConnectorDataTypes(Model):
    """The available data types for Threat Intelligence taxii client data
    connector.

    :param taxii_client: Data type for taxii client.
    :type taxii_client:
     ~securityinsights.models.TiTaxiiDataConnectorDataTypesTaxiiClient
    """

    _attribute_map = {
        'taxii_client': {'key': 'taxiiClient', 'type': 'TiTaxiiDataConnectorDataTypesTaxiiClient'},
    }

    def __init__(self, *, taxii_client=None, **kwargs) -> None:
        super(TiTaxiiDataConnectorDataTypes, self).__init__(**kwargs)
        self.taxii_client = taxii_client
