# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .resource_py3 import Resource


class WatchlistItem(Resource):
    """Represents a Watchlist Item in Azure Security Insights.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar id: Azure resource Id
    :vartype id: str
    :ivar name: Azure resource name
    :vartype name: str
    :ivar type: Azure resource type
    :vartype type: str
    :param created_by: Describes a user that created the watchlist
    :type created_by: ~securityinsights.models.UserInfo
    :param updated_by: Describes a user that updated the watchlist
    :type updated_by: ~securityinsights.models.UserInfo
    :param watchlist_item_name: Name of the watchlist item
    :type watchlist_item_name: str
    :param watchlist_item_pair: Required. A key-value pair for a watchlist
     item
    :type watchlist_item_pair: object
    :param entity_mapping: A key-value pair for a watchlist item entity
     mapping
    :type entity_mapping: object
    :param tenant_id: The tenantId to which this watchlist item belongs to
    :type tenant_id: str
    :param created_time_utc: The time the watchlist item was created
    :type created_time_utc: datetime
    :param last_updated_time_utc: The last time the watchlist item was updated
    :type last_updated_time_utc: datetime
    :param time_to_live_utc: The time to live for the watchlist item
    :type time_to_live_utc: datetime
    :param watchlist_item_type: The type of the watchlist item
    :type watchlist_item_type: str
    :param watchlist_id: Required. The watchlist id of the parent of this
     watchlist item
    :type watchlist_id: str
    """

    _validation = {
        'id': {'readonly': True},
        'name': {'readonly': True},
        'type': {'readonly': True},
        'watchlist_item_pair': {'required': True},
        'watchlist_id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'created_by': {'key': 'properties.createdBy', 'type': 'UserInfo'},
        'updated_by': {'key': 'properties.updatedBy', 'type': 'UserInfo'},
        'watchlist_item_name': {'key': 'properties.watchlistItemName', 'type': 'str'},
        'watchlist_item_pair': {'key': 'properties.watchlistItemPair', 'type': 'object'},
        'entity_mapping': {'key': 'properties.entityMapping', 'type': 'object'},
        'tenant_id': {'key': 'properties.tenantId', 'type': 'str'},
        'created_time_utc': {'key': 'properties.createdTimeUtc', 'type': 'iso-8601'},
        'last_updated_time_utc': {'key': 'properties.lastUpdatedTimeUtc', 'type': 'iso-8601'},
        'time_to_live_utc': {'key': 'properties.timeToLiveUtc', 'type': 'iso-8601'},
        'watchlist_item_type': {'key': 'properties.watchlistItemType', 'type': 'str'},
        'watchlist_id': {'key': 'properties.watchlistId', 'type': 'str'},
    }

    def __init__(self, *, watchlist_item_pair, watchlist_id: str, created_by=None, updated_by=None, watchlist_item_name: str=None, entity_mapping=None, tenant_id: str=None, created_time_utc=None, last_updated_time_utc=None, time_to_live_utc=None, watchlist_item_type: str=None, **kwargs) -> None:
        super(WatchlistItem, self).__init__(**kwargs)
        self.created_by = created_by
        self.updated_by = updated_by
        self.watchlist_item_name = watchlist_item_name
        self.watchlist_item_pair = watchlist_item_pair
        self.entity_mapping = entity_mapping
        self.tenant_id = tenant_id
        self.created_time_utc = created_time_utc
        self.last_updated_time_utc = last_updated_time_utc
        self.time_to_live_utc = time_to_live_utc
        self.watchlist_item_type = watchlist_item_type
        self.watchlist_id = watchlist_id
