# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from ._security_insights import SecurityInsights
from ._configuration import SecurityInsightsConfiguration
from .version import VERSION

__all__ = ['SecurityInsights', 'SecurityInsightsConfiguration']

__version__ = VERSION

