# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Serializer, Deserializer
from .operations.operations import Operations
from .operations.alert_rules_operations import AlertRulesOperations
from .operations.actions_operations import ActionsOperations
from .operations.alert_rule_templates_operations import AlertRuleTemplatesOperations
from .operations.cases_operations import CasesOperations
from .operations.comments_operations import CommentsOperations
from .operations.case_comments_operations import CaseCommentsOperations
from .operations.bookmarks_operations import BookmarksOperations
from .operations.case_relations_operations import CaseRelationsOperations
from .operations.bookmark_relations_operations import BookmarkRelationsOperations
from .operations.bookmark_operations import BookmarkOperations
from .operations.data_connectors_operations import DataConnectorsOperations
from .operations.data_connectors_check_requirements_operations import DataConnectorsCheckRequirementsOperations
from .operations.entities_operations import EntitiesOperations
from .operations.entities_relations_operations import EntitiesRelationsOperations
from .operations.entity_relations_operations import EntityRelationsOperations
from .operations.office_consents_operations import OfficeConsentsOperations
from .operations.product_settings_operations import ProductSettingsOperations
from .operations.cases_aggregations_operations import CasesAggregationsOperations
from .operations.entity_queries_operations import EntityQueriesOperations
from .operations.incidents_operations import IncidentsOperations
from .operations.incident_comments_operations import IncidentCommentsOperations
from .operations.incident_relations_operations import IncidentRelationsOperations
from . import models
from ._configuration import SecurityInsightsConfiguration


class SecurityInsights(SDKClient):
    """API spec for Microsoft.SecurityInsights (Azure Security Insights) resource provider

    :ivar config: Configuration for client.
    :vartype config: SecurityInsightsConfiguration

    :ivar operations: Operations operations
    :vartype operations: securityinsights.operations.Operations
    :ivar alert_rules: AlertRules operations
    :vartype alert_rules: securityinsights.operations.AlertRulesOperations
    :ivar actions: Actions operations
    :vartype actions: securityinsights.operations.ActionsOperations
    :ivar alert_rule_templates: AlertRuleTemplates operations
    :vartype alert_rule_templates: securityinsights.operations.AlertRuleTemplatesOperations
    :ivar cases: Cases operations
    :vartype cases: securityinsights.operations.CasesOperations
    :ivar comments: Comments operations
    :vartype comments: securityinsights.operations.CommentsOperations
    :ivar case_comments: CaseComments operations
    :vartype case_comments: securityinsights.operations.CaseCommentsOperations
    :ivar bookmarks: Bookmarks operations
    :vartype bookmarks: securityinsights.operations.BookmarksOperations
    :ivar case_relations: CaseRelations operations
    :vartype case_relations: securityinsights.operations.CaseRelationsOperations
    :ivar bookmark_relations: BookmarkRelations operations
    :vartype bookmark_relations: securityinsights.operations.BookmarkRelationsOperations
    :ivar bookmark: Bookmark operations
    :vartype bookmark: securityinsights.operations.BookmarkOperations
    :ivar data_connectors: DataConnectors operations
    :vartype data_connectors: securityinsights.operations.DataConnectorsOperations
    :ivar data_connectors_check_requirements: DataConnectorsCheckRequirements operations
    :vartype data_connectors_check_requirements: securityinsights.operations.DataConnectorsCheckRequirementsOperations
    :ivar entities: Entities operations
    :vartype entities: securityinsights.operations.EntitiesOperations
    :ivar entities_relations: EntitiesRelations operations
    :vartype entities_relations: securityinsights.operations.EntitiesRelationsOperations
    :ivar entity_relations: EntityRelations operations
    :vartype entity_relations: securityinsights.operations.EntityRelationsOperations
    :ivar office_consents: OfficeConsents operations
    :vartype office_consents: securityinsights.operations.OfficeConsentsOperations
    :ivar product_settings: ProductSettings operations
    :vartype product_settings: securityinsights.operations.ProductSettingsOperations
    :ivar cases_aggregations: CasesAggregations operations
    :vartype cases_aggregations: securityinsights.operations.CasesAggregationsOperations
    :ivar entity_queries: EntityQueries operations
    :vartype entity_queries: securityinsights.operations.EntityQueriesOperations
    :ivar incidents: Incidents operations
    :vartype incidents: securityinsights.operations.IncidentsOperations
    :ivar incident_comments: IncidentComments operations
    :vartype incident_comments: securityinsights.operations.IncidentCommentsOperations
    :ivar incident_relations: IncidentRelations operations
    :vartype incident_relations: securityinsights.operations.IncidentRelationsOperations

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param subscription_id: Azure subscription ID
    :type subscription_id: str
    :param str base_url: Service URL
    """

    def __init__(
            self, credentials, subscription_id, base_url=None):

        self.config = SecurityInsightsConfiguration(credentials, subscription_id, base_url)
        super(SecurityInsights, self).__init__(None, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2019-01-01-preview'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.operations = Operations(
            self._client, self.config, self._serialize, self._deserialize)
        self.alert_rules = AlertRulesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.actions = ActionsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.alert_rule_templates = AlertRuleTemplatesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.cases = CasesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.comments = CommentsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.case_comments = CaseCommentsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.bookmarks = BookmarksOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.case_relations = CaseRelationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.bookmark_relations = BookmarkRelationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.bookmark = BookmarkOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.data_connectors = DataConnectorsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.data_connectors_check_requirements = DataConnectorsCheckRequirementsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.entities = EntitiesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.entities_relations = EntitiesRelationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.entity_relations = EntityRelationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.office_consents = OfficeConsentsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.product_settings = ProductSettingsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.cases_aggregations = CasesAggregationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.entity_queries = EntityQueriesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.incidents = IncidentsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.incident_comments = IncidentCommentsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.incident_relations = IncidentRelationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
